global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'resource-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-service:8080']

  - job_name: 'storage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['storage-service:8083']

  - job_name: 'song-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['song-service:8081']

  - job_name: 'resource-processor-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['resource-processor-service:8086']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:80']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']
