server:
  port: 8083

spring:
  application:
    name: storage-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/Storage
          jwk-set-uri: http://keycloak:8085/auth/realms/Storage/protocol/openid-connect/certs
